[package]
name = "c-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
conv = "0.3.3"
itertools = "0.14.0"
lazy_static = "1.5.0"
regex = "1.11.1"
ryu = "1.0.20"
strum = "0.27.2"
strum_macros = "0.27.2"
