#!/bin/bash

output_name=c/$1
name=$(basename ${1%.c})
file=c/${1}.c
binary="cargo run --quiet --"

bat -l c --paging=never --theme "Visual Studio Dark+" $file

echo "Unoptimized code:"
bash -c "$binary $file -S" | bat -l asm --paging=never --theme "Visual Studio Dark+"
a=$(bash -c "$binary $file")
$output_name
unoptimized_result_code=$?
echo "Unoptimized result of $name: $unoptimized_result_code"
echo

echo "Code:"
bash -c "$binary $file -S --optimize" | bat -l asm --paging=never --theme "Visual Studio Dark+"
a=$(bash -c "$binary $file --optimize")
$output_name
result_code=$?
echo "Result of $name: $result_code"

rm c/$1
rm c/$1.s
