#!/bin/bash

### May change for other devices/languages being used ###
root_test_path=../../nlsandler/writing-a-c-compiler-tests
extra_args="--bitwise --increment --compound --goto --switch --nan"
binary_path=target/release/c-compiler
###

### REBUILD BINARY HERE ###
if [[ -n $VERBOSE ]]; then
	cargo build --release
else
	cargo build --quiet --release
fi
if [[ $? -ne 0 ]]; then
	exit 1
fi
###
if [[ -n $3 ]]; then
	# if a file name is specified, then run the verify script instead of the whole test suite
	./verify "$1" "$2" "$3"
	exit $?
fi

chapter=$1
stage=$2
if [[ -n $stage ]]; then
	results=$($root_test_path/test_compiler ./$binary_path --chapter "$chapter" --stage "$stage" $extra_args 2>&1)
else
	results=$($root_test_path/test_compiler ./$binary_path --chapter "$chapter" --increment $extra_args 2>&1)
fi

passing=true
for chapter_num in $(seq 1 $chapter); do
	chapter_banner_printed=false
	test_path=$root_test_path/tests/chapter_$chapter_num
	for i in $test_path/*; do

		j=$(echo $i | rev | cut -d/ -f1 | rev)
		output=$(echo $results | grep -o "chapter_$chapter_num/$j/[^\.]*" | cut -d" " -f1 | cut -d/ -f3- | uniq)
		if [[ -n $output ]]; then
			if ! $chapter_banner_printed; then
				echo ==============
				printf "= CHAPTER %-2s =\n" $chapter_num
				echo ==============
				chapter_banner_printed=true
			fi
			passing=false
			echo
			echo TESTS FAILED IN \"${j}\":
			echo -------
			if [[ -n $VERBOSE ]]; then
				echo "$output" | xargs -I{} bat $test_path/$j/{}.c
			else
				max_num_slashes=$(echo "$output" | awk -F/ '{print NF}' | sort -n | tail -1)
				output=$(echo "$output" | awk -F/ -v max=$max_num_slashes '{
					slashes = "";
					for (i=NF+1; i<=max; i++)
						slashes = slashes "/";
					print slashes $0
				}')
				printf "%s\n" "${output}" | column -t -s "/"
			fi
		fi
	done
done
if $passing; then
	echo "$results"
	exit 0
else
	exit 1
fi
