#!/bin/bash

chapter=$1
stage=$2
test_path=~/dev/nlsandler/writing-a-c-compiler-tests/tests/chapter_"$chapter"
if [[ -n $stage ]]; then
	results=$(~/dev/nlsandler/writing-a-c-compiler-tests/test_compiler ~/dev/AislingHeanue/c-compiler/target/debug/c-compiler --chapter "$chapter" --stage "$stage" 2>&1)
else
	results=$(~/dev/nlsandler/writing-a-c-compiler-tests/test_compiler ~/dev/AislingHeanue/c-compiler/target/debug/c-compiler --chapter "$chapter" 2>&1)
fi

passing=1
for i in $test_path/*
do
	j=$(echo $i | rev | cut -d/ -f1 | rev)
	output=$(echo $results | grep -o "[^/]*/[^/]*\.c " | awk -F/ -v i=$j '{if ($1 == i) print $2;}' | cut -d" " -f1)
	if [[ -n $output ]]; then
		passing=0
		echo TESTS FAILED IN \"${j}\":
		echo -------
		if [[ -n $VERBOSE ]]; then
			echo "$output" | xargs -I{} bat ${test_path}/${j}/{}
		else
			echo "$output"
		fi
	fi
done
if [[ $passing -eq 1 ]]; then
	echo "$results"
fi
