#!/bin/bash

### May change for other devices/languages being used ###
root_test_path="../../nlsandler/writing-a-c-compiler-tests"
binary="target/release/c-compiler"
###
if [[ -n "$COMMENTS" ]]; then
	binary="$binary --comments"
fi

# chapter=$1
stage=$2
name=$(echo "$3" | cut -d. -f1)

file=$(find "$root_test_path/tests/" -mindepth 3 -maxdepth 4 -name "$name.c")

if [ -z $file ]; then
	echo file not found
	exit 1
fi
bat $file

case $stage in
lex)
	bash -c "$binary $file --lex"
	;;
parse)
	# Pretty print the output tree as something like C.
	bash -c "$binary $file --validate > out && bat -l c < out; rm out"
	;;
validate)
	# Pretty print the output tree as something like C.
	bash -c "$binary $file --validate > out && bat -l c < out; rm out"
	;;
tacky)
	bash -c "$binary $file --tacky"
	;;
codegen)
	bash -c "$binary $file --codegen"
	;;
run)
	output_name=${file%.c}
	bash -c "$binary $file"
	# Run the outputted binary (if it exists)
	$output_name
	# Store the return code
	result_code=$?

	echo "Result of $name:"
	echo $result_code
	echo
	echo "Code:"
	# Print the generated assembly code
	bash -c "$binary $file -S" | bat -l asm --paging=never
	;;
esac
